config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :channels, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :channels, only: [:show] do
    resources :subscriptions, only: [:create]
  end
  resources :subscriptions, only: [:destroy, :index]
  resources :comments, only: [:destroy, :update] do
    resources :replies, only: [:create, :index]
  end
  resources :replies, only: [:destroy, :update]
  resources :posts do
    resources :comments, only: [:create, :index]
  end
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :subscriptions
  validates :name, presence: true, length: { minimum: 1 }
  validates :description, presence: true, length: { minimum: 1 }
end
 

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @channel = Channel.new
  end

  def create
    @channel = current_user.channels.create(channel_params)
    if @channel.valid?
      redirect_to channel_path(@channel)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @channel = Channel.find(params[:id])
    @posts = @channel.posts.order("created_at DESC").page(params[:page]).per_page(2)
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @posts = Post.where("title ILIKE ?", "%#{@title}%")
      @posts = @posts.order("created_at DESC").page(params[:page]).per_page(2)
    end
  end

  def edit
    @channel = Channel.find(params[:id])
    if current_user != @channel.user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def update
    @channel = Channel.find(params[:id])
    if current_user == @channel.user
      @channel.update_attributes(channel_params)
      if @channel.valid?
        redirect_to channel_path(@channel)
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    channel = Channel.find(params[:id])
    if current_user == channel.user
      channel.subscriptions.destroy_all
      channel.destroy
      redirect_to root_path
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name, :description)
  end

end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/edit.html.erb
<div class="container">
  <div class="box col-10">
    <%= simple_form_for @channel, url: channel_path(@channel) do |f|%>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.submit 'Post Edit', class: 'btn btn-primary make-it-green' %>
    <% end %>
  </div>
</div>

app/views/channels/new.html.erb
<div class="container">
  <div class="box col-10">
    <h2 class="make-it-green">Start A New Channel</h2>
    <br/>
    <%= simple_form_for @channel, url: channels_path do |f| %>
      <%= f.input :name %>
      <br />
      <%= f.input :description %>
      <%= f.submit 'Start', class: 'btn btn-primary make-it-green' %>
    <% end %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="page-content make-it-green">
  <h3><%= @channel.name %></h3>
  <br/>
  <h4><%= @channel.description %></h4>
</div>

<div class="channel-header-line"></div>

<div class="page-content make-it-green">

  <% if current_user && current_user == @channel.user %>
    <br/><br/>
    <%= link_to "Add a video", new_channel_post_path(@channel), class: "btn btn-primary make-it-green" %>
    <br/><br/>
    <%= link_to "Edit this channel", edit_channel_path(@channel), class: "btn btn-primary make-it-green" %>
    <br/><br/>
    <%= link_to "Delete this channel", channel_path(@channel), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary make-it-green" %>
  <% end %>

  <br/><br/>

  <% if current_user %>
    <%= react_component("Subscription", { root_with_channel_instance: polymorphic_url(@channel), current_user: current_user, channel: @channel }) %>
  <% end %>

  <br/><br/><br/>

  <%= simple_form_for :search, url: channel_path(@channel), method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :title, input_html: {value: ""} %>
    <%= f.submit "Search for a video", class: "btn btn-primary make-it-green" %>
  <% end %>

  <br/><br/>

  <h4><%= link_to "Show newest", channel_path(@channel), class: "make-it-green btn btn-primary" %></h4>

  <br/><br/>

  <% if !@channel.posts.count.zero? %>
    <div class="pagination">
      <% if @posts.previous_page %>
        <%= link_to "< Previous [", params.permit(:page).merge(:page => @posts.previous_page ) %>
      <% end %>
      Page <%= @posts.current_page %> of <%= @posts.total_pages %>
      <% if @posts.next_page %>
        <%= link_to "] Next >", params.permit(:page).merge(:page => @posts.next_page ) %>
      <% end %>
    </div>
    <br/>
  <% end %>

  <% for post in @posts %>
    <%= image_tag post.picture.url, class: "post-image" %>
    <div class="col-6 move-left">
      <%= link_to post.title, channel_post_path(@channel, post), class: "make-it-green post-link" %>
    </div>
    <br/>
  <% end %>

</div>

<br/><br/>