config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :channels, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :channels, only: [:show] do
    resources :subscriptions, only: [:create]
  end
  resources :subscriptions, only: [:destroy, :index]
  resources :comments, only: [:destroy, :update] do
    resources :replies, only: [:create, :index]
  end
  resources :replies, only: [:destroy, :update]
  resources :posts do
    resources :comments, only: [:create, :index]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per_page(2)
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @posts = Post.where("title ILIKE ?", "%#{@title}%")
      @posts = @posts.order("created_at DESC").page(params[:page]).per_page(2)
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="page-content">

  <% if !current_user %>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-primary make-it-green" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary make-it-green" %>
  <% else %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-primary make-it-green homepage-button" %>
    <%= link_to "Start A Channel", new_channel_path, class: "btn btn-primary make-it-green homepage-button" %>
  <% end %>

  <br/><br/>

  <% if current_user %>
    <div class="subscription-box">
      <% if !current_user.subscriptions.count.zero? %>
        <h4 class="make-it-green">Subscriptions</h4>
      <% else %>
        <h4 class="make-it-green">You have no subscriptions</h4>
      <% end %>

      <br/>

      <% current_user.subscriptions.each do |subscription| %>
        <% posts = [] %>
        <% subscription.channel.posts.reverse.each do |post| %>
          <% posts.push(post) %>
          <% break if posts.count == 3 %>
        <% end %>

        <%= react_component("VideoLinks", {
          root_with_channel_id: polymorphic_url(subscription.channel),
          posts: posts,
          channel: subscription.channel
        }) %>
      <% end %>
    </div>
  <% end %>

  <br/><br/>

  <%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :title, input_html: {value: ""} %>
    <%= f.submit "Search for a video", class: "btn btn-primary make-it-green" %>
  <% end %>

  <br/><br/>

  <%= link_to "Show newest", root_path, class: "btn btn-primary make-it-green" %>

  <br/><br/>

  <% if !@posts.count.zero? %>
    <div class="pagination pagination-text make-it-green">
      <% if @posts.previous_page %>
        <%= link_to "< Previous [", params.permit(:page).merge(:page => @posts.previous_page ) %>
      <% end %>
      Page <%= @posts.current_page %> of <%= @posts.total_pages %>
      <% if @posts.next_page %>
        <%= link_to "] Next >", params.permit(:page).merge(:page => @posts.next_page ) %>
      <% end %>
    </div>
    <br/>
  <% end %>

  <% @posts.each do |post| %>
    <div><%= image_tag post.picture.url, class: "landing-page-post-image" %></div>
    <h3 class="video-link"><%= link_to "#{post.title}", channel_post_path(post.channel.id, post), class: "make-it-green" %></h3>
    <h5><%= link_to post.channel.name, channel_path(post.channel), class: "make-it-green" %></h5>
    <br/><br/>
  <% end %>

</div>