config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :channels, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :channels, only: [:show] do
    resources :subscriptions, only: [:create]
  end
  resources :subscriptions, only: [:destroy, :index]
  resources :comments, only: [:destroy, :update] do
    resources :replies, only: [:create, :index]
  end
  resources :replies, only: [:destroy, :update]
  resources :posts do
    resources :comments, only: [:create, :index]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :channel
  has_many :comments
  mount_uploader :picture, PictureUploader
  mount_uploader :video, VideoUploader
  validates :title, presence: true, length: { minimum: 1 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @channel = Channel.find(params[:channel_id])
    if current_user == @channel.user
      @post = Post.new
    else
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def create
    channel = Channel.find(params[:channel_id])
    if current_user == channel.user
      post = channel.posts.create(post_params)
      if post.valid?
        redirect_to channel_post_path(channel, post)
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def show
    @channel = Channel.find(params[:channel_id])
    @post = Post.find(params[:id])
  end

  def edit
    @channel = Channel.find(params[:channel_id])
    @post = Post.find(params[:id])
    if current_user != @channel.user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def update
    channel = Channel.find(params[:channel_id])
    @post = Post.find(params[:id])
    if current_user == channel.user
      @post.update_attributes(post_params)
      if @post.valid?
        redirect_to channel_post_path(channel, @post)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def destroy
    channel = Channel.find(params[:channel_id])
    post = Post.find(params[:id])
    if current_user == channel.user
      post.destroy
      redirect_to channel_path(channel)
    else
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :picture, :video)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <div class="box col-10">
    <h2>Edit Your Post</h2>
    <%= simple_form_for @post, url: channel_post_path(@channel, @post) do |f|%>
      <%= f.input :title %>
      <br/>
      <%= f.input :description %>
      <%= f.submit 'Confirm', class: 'btn btn-primary make-it-green' %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="box col-10">
    <h2 class="make-it-green">Upload Video</h2>
    <br/>
    <%= simple_form_for @post, url: channel_posts_path(@channel) do |f|%>
      <%= f.input :title %>
      <br />
      <%= f.input :description %>
      <%= f.input :picture %>
      <%= f.input :video %>
      <%= f.submit 'Upload', class: 'btn btn-primary make-it-green' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="page-content">

  <br/><br/>

  <video id="my-video" class="video-js vjs-big-play-centered" controls preload="auto" width="900" height="500"
    poster="<%= image_path(@post.picture) %>" data-setup="{}">
    <source src="<%= @post.video.to_s %>" type='video/mp4'>
    <noscript>
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
    </noscript>
  </video>

  <div class="make-it-green">
    <br/>
    <div class="col-6 move-left">
      <h3><%= @post.title %></h3>
    </div>
    <br/>
    <% if current_user == @channel.user %>
      <h4><%= link_to "Edit post", edit_channel_post_path(@channel, @post), class: "make-it-green" %></h4>
      <h4><%= link_to "Delete post", channel_post_path(@channel, @post), method: :delete, data: { confirm: "Are you sure?" }, class: "make-it-green" %></h4>
    <% end %>
    <br/>
    <h4><%= link_to "Go to #{@channel.name} videos", channel_path(@channel), class: "make-it-green" %></h4>
    <br/>
    <%= react_component("Description", { description: @post.description }) %>
    <br/>
    <%= react_component("Comments", { root_with_post_instance: polymorphic_url(@post), current_user: current_user, post: @post }) %>
  </div>

</div>

<br/><br/><br/><br/>